# Site settings
title:            "Michael in Beta | Design, code and startups | Newcastle Australia"
email:            michael@metaset.com.au
description:      "Michael in Beta is a blog about web design, UX, code and startups. Written by Michael Troy from Newcastle Australia."
baseurl: ""
url:              "http://michaelinbeta.com"
production_url:   www.michaelinbeta.com
permalink:        :title
post_dirs:        false

twitter_username: michaeltroy
github_username:  michaeltroy

# Build settings
markdown: kramdown

# Syntax highlighting
highlighter: pygments

# Post formatting
excerpt_separator: <!--more-->

# Timezone
timezone: Australia/Sydney

# Text encoding
encoding: utf-8

# Exclude folders
exclude:
    [project,
    design/components,
    design/ui,
    design/node_modules,
    design/gulpfile.js,
    design/package.json,
    design/README.md]
