# Site settings
title: mikeytroy.com
email: michael@metaset.com.au
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikeytroy.com" # the base hostname & protocol for your site
twitter_username: michaeltroy
github_username:  michaeltroy

# Build settings
markdown: kramdown

# Syntax highlighting
highlighter: pygments

# Timezone
timezone: Australia/Sydney

# Text encoding
encoding: utf-8

# Exclude folders
exclude: 
    [project, 
    design/components, 
    design/node_modules, 
    design/gulpfile.js,
    design/package.json, 
    design/README.md]
